<template>
  <div :class="classes">
    <div id="media-viewer-container">
      <div class="players" id="player1-container">
        <div class="media-wrapper">
          <video
            :src="src"
            class="mejs__player"
            poster="https://static.library.ucla.edu/video_icon.svg"
            data-mejsoptions='{"alwaysShowControls": "true"}'
          ></video>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
/* eslint-disable */

export default {
  props: {
    src: {
      type: String,
      default: ""
    }
  },
  computed: {
    classes() {
      return ["mejs", { "show-player": this.src }];
    }
  },
  beforeMount() {
    let mejsScript = document.createElement("script");
    mejsScript.setAttribute("src", "/mejs/mediaelement-and-player.js");
    document.head.appendChild(mejsScript);

    // let jqueryScript = document.createElement("script");
    // jqueryScript.setAttribute(
    //   "src",
    //   "https://code.jquery.com/jquery-3.6.0.min.js"
    // );
    //
    // jqueryScript.setAttribute(
    //   "integrity",
    //   "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    // );
    // jqueryScript.setAttribute("crossorigin", "anonymous");
    // document.head.appendChild(jqueryScript);

    let jqueryScript = document.createElement("script");
    jqueryScript.setAttribute("src", "/jquery/jquery.js");
    document.head.appendChild(jqueryScript);
    // document.getElementsByClassName("media-wrapper").innerHtml
    // document.onreadystatechange = () => {
    //   if (document.readyState == "complete") {
    //     console.log("Page completed with image and files!");
    //     // fetch to next page or some code
    //   }
    // };
  }
};
</script>

<!-- Have to remove scoped attribute for css generated by javascript? -->
<style>
.mejs {
  width: 1300px;
  height: 668px;
}
.mejs__player {
  height: 100%;
  width: 100%;
}
@import "/mejs/mediaelementplayer.css";
</style>
